/**
 * engine/page-geometry — generates @page CSS from design tokens
 *
 * CSS custom properties do not reliably cascade into @page descriptors
 * across paged engines (spec §3.4 / D-08b). This module reads token
 * values from the DOM via getComputedStyle and writes a concrete @page
 * block at render time, before Paged.js processes the document.
 *
 * Usage
 * -----
 * In PagedPreview.tsx (parent frame, which has the same token CSS loaded):
 *
 *   import { generatePageGeometry } from '../../engine/page-geometry';
 *   const pageCSS = generatePageGeometry(document.documentElement);
 *   // inline pageCSS into the srcdoc <style> block
 *
 * The parent frame shares the same token CSS, so custom property values
 * are identical to what the iframe would read.
 */

export interface PageGeometry {
  width: string;
  height: string;
  marginTop: string;
  marginBottom: string;
  marginInside: string;
  marginOutside: string;
}

/**
 * Read a CSS custom property from an element via getComputedStyle.
 * Returns the trimmed value, or the fallback if the property is empty.
 */
function readProp(style: CSSStyleDeclaration, name: string, fallback: string): string {
  const val = style.getPropertyValue(name).trim();
  return val !== '' ? val : fallback;
}

/**
 * Read the page geometry token values from the computed style of `root`.
 *
 * Falls back to the spec-default 6×9 in book dimensions if any token is
 * missing (matches the :root defaults in tokens/global.css).
 */
export function readPageGeometry(root: Element): PageGeometry {
  const style = getComputedStyle(root);
  return {
    width: readProp(style, '--book-trim-width', '6in'),
    height: readProp(style, '--book-trim-height', '9in'),
    marginTop: readProp(style, '--book-margin-top', '0.75in'),
    marginBottom: readProp(style, '--book-margin-bottom', '0.875in'),
    marginInside: readProp(style, '--book-margin-inside', '0.875in'),
    marginOutside: readProp(style, '--book-margin-outside', '0.625in'),
  };
}

/**
 * Generate a CSS string containing the @page rules for a book with the
 * given geometry.
 *
 * Three rules are emitted:
 *   @page        — sets the page size (required by Paged.js for all pages)
 *   @page :right — recto (right, odd-numbered) pages
 *   @page :left  — verso (left, even-numbered) pages
 *
 * For a standard LTR right-opening book:
 *   - Recto (right, odd) page:  spine is on the LEFT  → margin-left = inside, margin-right = outside
 *   - Verso (left, even) page:  spine is on the RIGHT → margin-left = outside, margin-right = inside
 *
 * Top and bottom margins are identical on both page types.
 */
export function generatePageCSS(geometry: PageGeometry): string {
  const { width, height, marginTop, marginBottom, marginInside, marginOutside } = geometry;

  return [
    `/* Generated by engine/page-geometry — do not hand-edit */`,
    // size descriptor is in the unqualified @page only — :right and :left inherit
    // it via page-descriptor cascade (CSS Paged Media spec). Duplicating it in
    // named-page rules is unnecessary and could cause specificity confusion.
    `@page {`,
    `  size: ${width} ${height};`,
    `}`,
    ``,
    `@page :right {`,
    `  margin-top: ${marginTop};`,
    `  margin-bottom: ${marginBottom};`,
    `  margin-left: ${marginInside};`,
    `  margin-right: ${marginOutside};`,
    `}`,
    ``,
    `@page :left {`,
    `  margin-top: ${marginTop};`,
    `  margin-bottom: ${marginBottom};`,
    `  margin-left: ${marginOutside};`,
    `  margin-right: ${marginInside};`,
    `}`,
  ].join('\n');
}

/**
 * Read page geometry tokens from `root` and return the complete @page CSS.
 *
 * Convenience wrapper that combines readPageGeometry + generatePageCSS.
 * Pass `document.documentElement` from any frame that has the token CSS loaded.
 */
export function generatePageGeometry(root: Element): string {
  return generatePageCSS(readPageGeometry(root));
}

/**
 * @deprecated Not compatible with the srcdoc architecture — geometry must be
 * inlined before the Paged.js polyfill script (Quirk Q2). Use
 * generatePageGeometry() + buildSrcdoc() instead. Kept for potential
 * server-side rendering use cases.
 *
 * Inject (or replace) a <style id="page-geometry"> element in doc.head
 * with the @page rules derived from the page geometry tokens found on
 * doc.documentElement.
 *
 * Call this BEFORE loading Paged.js to ensure the @page block is
 * present when the polyfill first reads the stylesheet cascade.
 */
export function injectPageGeometry(doc: Document): void {
  const css = generatePageGeometry(doc.documentElement);
  let el = doc.getElementById('page-geometry') as HTMLStyleElement | null;
  if (!el) {
    el = doc.createElement('style');
    el.id = 'page-geometry';
    doc.head.appendChild(el);
  }
  el.textContent = css;
}
