/**
 * engine/page-geometry — generates @page CSS from design tokens
 *
 * CSS custom properties do not reliably cascade into @page descriptors
 * across paged engines (spec §3.4 / D-08b). This module reads token
 * values from the DOM via getComputedStyle and writes a concrete @page
 * block at render time, before Paged.js processes the document.
 *
 * Usage
 * -----
 * In PagedPreview.tsx (parent frame, which has the same token CSS loaded):
 *
 *   import { generatePageGeometry } from '../../engine/page-geometry';
 *   const pageCSS = generatePageGeometry(document.documentElement);
 *   // inline pageCSS into the srcdoc <style> block
 *
 * The parent frame shares the same token CSS, so custom property values
 * are identical to what the iframe would read.
 */

export interface PageGeometry {
  width: string;
  height: string;
  marginTop: string;
  marginBottom: string;
  marginInside: string;
  marginOutside: string;
}

/**
 * Read a CSS custom property from an element via getComputedStyle.
 * Returns the trimmed value, or the fallback if the property is empty.
 */
function readProp(style: CSSStyleDeclaration, name: string, fallback: string): string {
  const val = style.getPropertyValue(name).trim();
  return val !== '' ? val : fallback;
}

/**
 * Read the page geometry token values from the computed style of `root`.
 *
 * Falls back to the spec-default 6×9 in book dimensions if any token is
 * missing (matches the :root defaults in tokens/global.css).
 */
export function readPageGeometry(root: Element): PageGeometry {
  const style = getComputedStyle(root);
  return {
    width: readProp(style, '--book-trim-width', '6in'),
    height: readProp(style, '--book-trim-height', '9in'),
    marginTop: readProp(style, '--book-margin-top', '0.75in'),
    marginBottom: readProp(style, '--book-margin-bottom', '0.875in'),
    marginInside: readProp(style, '--book-margin-inside', '0.875in'),
    marginOutside: readProp(style, '--book-margin-outside', '0.625in'),
  };
}

/**
 * Generate a CSS string containing the @page rules for a book with the
 * given geometry.
 *
 * Two rules are emitted:
 *   @page        — default / recto (right, odd-numbered) pages
 *   @page :left  — verso (left, even-numbered) pages
 *
 * For a standard LTR book:
 *   - Recto (right, odd) page:  left side = inside (spine), right side = outside
 *   - Verso (left, even) page:  left side = outside,        right side = inside (spine)
 *
 * IMPORTANT — known inversion issue (see Task 13: recto/verso margin model):
 * The margin assignments below may be inverted. The current implementation
 * places `marginOutside` on `margin-left` and `marginInside` on `margin-right`
 * for the default @page rule, but for a recto page the left side IS the spine
 * (inside), so the assignments should be the other way around. Task 13's
 * implementer should verify and correct the mapping here and in @page :left.
 */
export function generatePageCSS(geometry: PageGeometry): string {
  const { width, height, marginTop, marginBottom, marginInside, marginOutside } = geometry;

  return [
    `/* Generated by engine/page-geometry — do not hand-edit */`,
    `@page {`,
    `  size: ${width} ${height};`,
    `  margin-top: ${marginTop};`,
    `  margin-bottom: ${marginBottom};`,
    `  margin-left: ${marginOutside};`,
    `  margin-right: ${marginInside};`,
    `}`,
    ``,
    `@page :left {`,
    `  margin-left: ${marginInside};`,
    `  margin-right: ${marginOutside};`,
    `}`,
  ].join('\n');
}

/**
 * Read page geometry tokens from `root` and return the complete @page CSS.
 *
 * Convenience wrapper that combines readPageGeometry + generatePageCSS.
 * Pass `document.documentElement` from any frame that has the token CSS loaded.
 */
export function generatePageGeometry(root: Element): string {
  return generatePageCSS(readPageGeometry(root));
}

/**
 * Inject (or replace) a <style id="page-geometry"> element in doc.head
 * with the @page rules derived from the page geometry tokens found on
 * doc.documentElement.
 *
 * Call this BEFORE loading Paged.js to ensure the @page block is
 * present when the polyfill first reads the stylesheet cascade.
 */
export function injectPageGeometry(doc: Document): void {
  const css = generatePageGeometry(doc.documentElement);
  let el = doc.getElementById('page-geometry') as HTMLStyleElement | null;
  if (!el) {
    el = doc.createElement('style');
    el.id = 'page-geometry';
    doc.head.appendChild(el);
  }
  el.textContent = css;
}
